[PHP]
extension_dir = "ext"
memory_limit = 512M
max_execution_time = 300
upload_max_filesize = 256M
post_max_size = 256M
variables_order = "GPCS"
date.timezone = "Asia/Shanghai"

extension=curl
extension=fileinfo
extension=mbstring
extension=openssl
extension=pdo_sqlite
extension=sqlite3
